# Generated by Django 2.0.2 on 2018-03-16 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.IntegerField(default=0)),
                ('coin_name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=10)),
                ('block_chain', models.CharField(max_length=10)),
                ('search_terms', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico_id', models.IntegerField(default=0)),
                ('ico_name', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('description', models.TextField()),
                ('search_terms', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OverallSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_tweets', models.IntegerField(default=0)),
                ('num_searches', models.IntegerField(default=0)),
                ('num_articles', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocounter.Coin')),
            ],
        ),
        migrations.CreateModel(
            name='SocialCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_tweets', models.IntegerField(default=0)),
                ('num_searches', models.IntegerField(default=0)),
                ('num_articles', models.IntegerField(default=0)),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocounter.Coin')),
            ],
        ),
        migrations.CreateModel(
            name='SocialIco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_tweets', models.IntegerField(default=0)),
                ('num_searches', models.IntegerField(default=0)),
                ('num_articles', models.IntegerField(default=0)),
                ('ico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocounter.Ico')),
            ],
        ),
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocounter.Coin')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
