# Generated by Django 2.0.2 on 2018-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocounter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ico',
            name='id',
        ),
        migrations.AddField(
            model_name='price',
            name='circ_supply',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='price',
            name='percent_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ico',
            name='ico_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ico',
            name='ico_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
