# Generated by Django 2.0.2 on 2018-04-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocounter', '0003_auto_20180405_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ico',
            name='ico_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
