# Generated by Django 2.0.3 on 2018-04-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocounter', '0003_auto_20180405_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='circ_supply',
            field=models.BigIntegerField(default=0),
        ),
    ]
