# Generated by Django 2.0.3 on 2018-04-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocounter', '0004_auto_20180405_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ico',
            old_name='end',
            new_name='ico_end',
        ),
        migrations.RenameField(
            model_name='ico',
            old_name='start',
            new_name='ico_start',
        ),
    ]
