# Generated by Django 2.0.2 on 2018-04-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocounter', '0004_auto_20180408_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ico',
            old_name='end',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='ico',
            old_name='start',
            new_name='startDate',
        ),
    ]
