# Generated by Django 2.0.2 on 2018-04-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocounter', '0005_auto_20180409_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='circ_supply',
            field=models.BigIntegerField(default=0),
        ),
    ]
