# Generated by Django 2.0.3 on 2018-04-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocounter', '0006_auto_20180409_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ico',
            old_name='endDate',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='ico',
            old_name='startDate',
            new_name='startdate',
        ),
    ]
