# Generated by Django 2.0.3 on 2018-04-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocounter', '0007_auto_20180410_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overallsocial',
            old_name='num_searches',
            new_name='num_likes',
        ),
        migrations.RenameField(
            model_name='socialcoin',
            old_name='num_searches',
            new_name='num_likes',
        ),
        migrations.RenameField(
            model_name='socialico',
            old_name='num_searches',
            new_name='num_likes',
        ),
        migrations.AddField(
            model_name='overallsocial',
            name='num_subs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialcoin',
            name='num_subs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialico',
            name='num_subs',
            field=models.IntegerField(default=0),
        ),
    ]
