# Generated by Django 2.0.3 on 2018-04-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocounter', '0009_generalmarket_watchico'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallsocial',
            name='num_trends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialcoin',
            name='num_trends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialico',
            name='num_trends',
            field=models.IntegerField(default=0),
        ),
    ]
